num1= int(input("ENTER THE VALUE OF A  "))
num2= int(input("ENTER THE VALUE OF B  "))
print("YOU ENTER ",num1,"  AND  ", num2 )
print( " ADDITION       OF A AND B =",num1+num2)
print( " SUBTRACTION    OF A AND B =",num1-num2)
print( " MULTIPLICATION OF A AND B =",num1*num2)
print( " DIVISION       OF A AND B =",num1/num2)
print( " FLOOR          OF A AND B =",num1//num2)
print( " REMINDER       OF A AND B =",num1%num2)
